-- ProcessLang Lens: ExampleLens
-- Domain: An example domain for testing the automatic lens writer.
-- Generated by Eva

local lens = {}
lens.name = "ExampleLens"
lens.domain = "An example domain for testing the automatic lens writer."
lens.operators = {
    FLOW     = "Example flow description.",
    CONNECT  = "Example connect description.",
    DISSOLVE = "Example dissolve description.",
    ENCODE   = "Example encode description.",
    CHOOSE   = "Example choose description.",
    OBSERVE  = "Example observe description.",
    CYCLE    = "Example cycle description.",
    LOGIC    = "Example logic description.",
    RUNTIME  = "Example runtime description.",
    MANIFEST = "Example manifest description."
}
return lens