-- ProcessLang Lens: harmonicflow
-- Generated by Eva

local lens = {}
lens.name = "HarmonicFlow"
lens.domain = "music composition and analysis"
lens.operators = {
    FLOW     = "movement through musical time, progression of phrases and sections",
    CONNECT  = "harmonic relationships, voice leading, melodic connections",
    DISSOLVE = "resolution of tension, fade-outs, transitional decay",
    ENCODE   = "representing musical ideas as notation, MIDI, or abstract structures",
    CHOOSE   = "selecting notes, chords, scales, or compositional paths",
    OBSERVE  = "active listening, spectral analysis, pattern recognition",
    CYCLE    = "repetition, loops, rhythmic cycles, harmonic sequences",
    LOGIC    = "rules of counterpoint, harmony, formal structures",
    RUNTIME  = "real-time performance, improvisation, adaptive systems",
    MANIFEST = "rendering as audible sound, score, or performance"
}
return lens